# Generated by Django 3.2.1 on 2022-06-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField()),
                ('updated_on', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['-created_on'],
                'get_latest_by': ['created_on'],
            },
        ),
    ]
